### ISSUE TITLE
有计划升级到ue5版本么

### ISSUE THREAD

**Issue by nevermorewish** [puerts/EasyEditor_ImGui#1]
有计划升级到ue5版本么

**Comment by chexiongsheng** [comment]
这只是 https://github.com/ZhuRong-HomoStation/UEImgui 导出到ts，这支持ue5.3应该没啥问题，现在问题是UEImgui在5.3都没编译过。

**Comment by huzhangyang** [comment]
目前的版本需要把buid.cs中改为PCHUsage = PCHUsageMode.NoPCHs来解决和https://github.com/puerts/EasyEditorPlugin/issues/2 相同的问题；但仍有一些其他编译错误
![image](https://github.com/puerts/EasyEditor_ImGui/assets/5735704/e4b28d4c-6b43-47e2-a2f4-602ccbff6f61)
UEImgui编译的话需要按照这个原则改一下（https://inlet511.github.io/posts/ue5-rendering-updates/）：
“RHICreateVertexBuffer, RHICreateIndexBuffer都统一为RHICreateBuffer FVertexBufferRHIRef, FIndexBufferRHIRef都统一为FBufferRHIRef RHILockVertexBuffer，RHILockIndexBuffer都统一为RHILockBuffer RHIUnlockVertexBuffer, RHIUnlockIndexBuffer都统一为RHIUnlockBuffer”

**Comment by chexiongsheng** [comment]
> 目前的版本需要把buid.cs中改为PCHUsage = PCHUsageMode.NoPCHs来解决和[puerts/EasyEditorPlugin#2](https://github.com/puerts/EasyEditorPlugin/issues/2) 相同的问题；但仍有一些其他编译错误 ![image](https://private-user-images.githubusercontent.com/5735704/298444395-e4b28d4c-6b43-47e2-a2f4-602ccbff6f61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDQ1MzgsIm5iZiI6MTcwNTkwNDIzOCwicGF0aCI6Ii81NzM1NzA0LzI5ODQ0NDM5NS1lNGIyOGQ0Yy02YjQzLTQ3ZTItYTJmNC02MDJjY2JmZjZmNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMDYxNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRiOTAwZWY2MThmNmIyODA1NmU4MWU3MDZhYjBjYzU0YmM0MzA4YjA0NjU3OTE3YzA4OWMyN2M3NzJlMWVlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2fU2VwQoEpCJHDT1GdpdDp3na2dM532fhFao8if2rok) UEImgui编译的话需要按照这个原则改一下（[https://inlet511.github.io/posts/ue5-rendering-updates/）：](https://inlet511.github.io/posts/ue5-rendering-updates/%EF%BC%89%EF%BC%9A) “RHICreateVertexBuffer, RHICreateIndexBuffer都统一为RHICreateBuffer FVertexBufferRHIRef, FIndexBufferRHIRef都统一为FBufferRHIRef RHILockVertexBuffer，RHILockIndexBuffer都统一为RHILockBuffer RHIUnlockVertexBuffer, RHIUnlockIndexBuffer都统一为RHIUnlockBuffer”

你把UEImgui搞好，我可以把这个搞好

**Comment by huzhangyang** [comment]
UEImgui搞好了，提在这里了 https://github.com/ZhuRong-HomoStation/UEImgui/issues/17

**Comment by chexiongsheng** [comment]
你直接clone来修改还好些，然后提个PR。没过我改为引用你的

**Comment by chexiongsheng** [comment]
目前编译能通过，但Demo执行到：https://github.com/puerts/EasyEditorPluginDemo/blob/master/EasyEditorDemo/src/Main.ts#L69会报toolbar是undefined，我估计是工具栏得用别的方式来获取。
前面的菜单倒是初始化成功了，但执行后会崩到渲染那，可能UEImgui那没兼容好。

**Comment by huzhangyang** [comment]
LevelEditorToolBar这个 42行需要改为
`const toolbar = menus.FindMenu('LevelEditor.LevelEditorToolBar.User')`

Main.ts 103行需要改为                 
`const selected_objects = context_menu_context.GetSelectedObjects();`
（只是为了通过编译，因为这也是个Deprecated的API，并且会造成资源加载，正式用需要改为SelectedAssets并且做一系列对应修改）

崩溃我这里没有出现，怀疑和具体工程的设置有关，因为UE5默认使用SM6了，所以ImguiDrawer.cpp中241、242行我改为了

```
TShaderMapRef<FImguiShaderVs> Vs(GetGlobalShaderMap(ERHIFeatureLevel::SM6));
TShaderMapRef<FImguiShaderPs> Ps(GetGlobalShaderMap(ERHIFeatureLevel::SM6));
```

如果项目使用的是SM5或者其他的，可能这里也要对应改一下

**Comment by chexiongsheng** [comment]
> LevelEditorToolBar这个 42行需要改为 `const toolbar = menus.FindMenu('LevelEditor.LevelEditorToolBar.User')`
> 
> Main.ts 103行需要改为 `const selected_objects = context_menu_context.GetSelectedObjects();` （只是为了通过编译，因为这也是个Deprecated的API，并且会造成资源加载，正式用需要改为SelectedAssets并且做一系列对应修改）
> 
> 崩溃我这里没有出现，怀疑和具体工程的设置有关，因为UE5默认使用SM6了，所以ImguiDrawer.cpp中241、242行我改为了
> 
> ```
> TShaderMapRef<FImguiShaderVs> Vs(GetGlobalShaderMap(ERHIFeatureLevel::SM6));
> TShaderMapRef<FImguiShaderPs> Ps(GetGlobalShaderMap(ERHIFeatureLevel::SM6));
> ```
> 
> 如果项目使用的是SM5或者其他的，可能这里也要对应改一下

在哪里能看到这设置？

**Comment by huzhangyang** [comment]
> > LevelEditorToolBar这个 42行需要改为 `const toolbar = menus.FindMenu('LevelEditor.LevelEditorToolBar.User')`
> > Main.ts 103行需要改为 `const selected_objects = context_menu_context.GetSelectedObjects();` （只是为了通过编译，因为这也是个Deprecated的API，并且会造成资源加载，正式用需要改为SelectedAssets并且做一系列对应修改）
> > 崩溃我这里没有出现，怀疑和具体工程的设置有关，因为UE5默认使用SM6了，所以ImguiDrawer.cpp中241、242行我改为了
> > ```
> > TShaderMapRef<FImguiShaderVs> Vs(GetGlobalShaderMap(ERHIFeatureLevel::SM6));
> > TShaderMapRef<FImguiShaderPs> Ps(GetGlobalShaderMap(ERHIFeatureLevel::SM6));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果项目使用的是SM5或者其他的，可能这里也要对应改一下
> 
> 在哪里能看到这设置？

没搞错的话应该是这里
![image](https://github.com/puerts/EasyEditor_ImGui/assets/5735704/243cc543-0fed-4a66-833f-b0f96d439acd)

**Comment by chexiongsheng** [comment]
我的确实是sm5，设置成sm6后，运行会崩溃：
~~~bash
LoginId:c691a65a4405f9fe1b11afa90aa2015b
EpicAccountId:0c955e33e783465997d159fd4a18439f

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000000000000000b

UnrealEditor_RenderCore!FGlobalShaderMap::GetShader() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\GlobalShader.cpp:605]
UnrealEditor_UEImgui!FImguiDrawer::DrawRenderThread() [D:\UnrealProjects\ue5\EasyEditorPluginDemo\Plugins\UEImgui\Source\UEImgui\Private\Render\ImguiDrawer.cpp:241]
UnrealEditor_SlateRHIRenderer!FSlateRHIRenderingPolicy::DrawElements() [D:\build\++UE5\Sync\Engine\Source\Runtime\SlateRHIRenderer\Private\SlateRHIRenderingPolicy.cpp:1303]
UnrealEditor_SlateRHIRenderer!RenderSlateBatch() [D:\build\++UE5\Sync\Engine\Source\Runtime\SlateRHIRenderer\Private\SlateRHIRenderer.cpp:984]
UnrealEditor_SlateRHIRenderer!FSlateRHIRenderer::DrawWindow_RenderThread() [D:\build\++UE5\Sync\Engine\Source\Runtime\SlateRHIRenderer\Private\SlateRHIRenderer.cpp:1202]
UnrealEditor_SlateRHIRenderer!TEnqueueUniqueRenderCommandType<`FSlateRHIRenderer::DrawWindows_Private'::`51'::SlateDrawWindowsCommandName,`FSlateRHIRenderer::DrawWindows_Private'::`51'::<lambda_4> >::DoTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Public\RenderingThread.h:209]
UnrealEditor_SlateRHIRenderer!TGraphTask<TEnqueueUniqueRenderCommandType<`FSlateRHIRenderer::DrawWindows_Private'::`51'::SlateDrawWindowsCommandName,`FSlateRHIRenderer::DrawWindows_Private'::`51'::<lambda_4> > >::ExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:1265]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksNamedThread() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:758]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:649]
UnrealEditor_RenderCore!RenderingThreadMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:411]
UnrealEditor_RenderCore!FRenderingThread::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:537]
UnrealEditor_Core!FRunnableThreadWin::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:149]
~~~

**Comment by chexiongsheng** [comment]
设置成sm5，然后GetGlobalShaderMap也改成传sm5是不崩的。
